// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clipboard} from '../models';

export function SetClipboard(arg1:clipboard.Format,arg2:string):Promise<void>;
