name: "Build PeerClip"

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  prepare-release:
    if: startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Create release (draft)
        uses: softprops/action-gh-release@v2
        with:
          name: PeerClip - ${{ github.ref }}
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build:
    needs: 
      - "prepare-release"

    strategy:
      matrix:
        platform: [windows, macos]
        go-version: [1.23]

    runs-on: ${{ matrix.platform }}-latest

    permissions:
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app
        run: |
          wails build -o PeerClip-${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platform }}
          path: build/bin/*

  update-release:
    if: startsWith(github.event.ref, 'refs/tags/')

    needs: 
      - "build"

    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Merge artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: Append artifacts to release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*
