name: "Build PeerClip"

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        platform: [windows, macos]
        go-version: [1.23]

    runs-on: ${{ matrix.platform }}-latest

    permissions:
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app
        run: |
          wails build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/bin/*

  release:
    # if: startsWith(github.event.ref, 'refs/tags/')

    needs: 
      - "build"

    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      
      - name: Compress artifacts
        run: |
          mkdir compress
          cd artifacts
          ls | xargs -I {} sh -c "cd {}; zip -r ../../compress/PeerClip-{}.zip *"
      
      - name: List files # For debug only
        run: |
          find . -type f -exec echo {} \;

      # - name: Create release (draft)
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: PeerClip - ${{ github.ref }}
      #     tag_name: ${{ github.ref }}
      #     generate_release_notes: true
      #     draft: true
      #     files: |
      #       compress/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
